{% set name = "aiohue" %}
{% set version = "4.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiohue-{{ version }}.tar.gz
  sha256: 9a50dfed1174dfc901ebbd29f1d0da5ce02c9704282ece004de40fce20774783

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - asyncio-throttle
    - awesomeversion

test:
  imports:
    - aiohue
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/home-assistant-libs/aiohue
  summary: Python module to talk to Philips Hue.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
